api:
  insecure: true
  dashboard: true
# provider docker
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    
accessLog:
  format: txt
  filePath: /etc/traefik/
  bufferingSize: 100
